apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  namespace: example
  labels:
    app: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: nginx
        image: alpine:3.10.2
        args:
        - sleep
        - 1d